### ISSUE TITLE
Teachback Groups 

### ISSUE THREAD

**Issue by brianamarie** [githubschool/Nov-6#2]
## Groups

|  Group | Zoom URL | Members | 
|  ------ | ------ | ------ | 
| 1 | https://github.zoom.us/j/563145373 |  |
| 2 | https://github.zoom.us/j/426746590 |Deepak Dinakaran, <br>Hazem Bayado, <br> Saeed Albarhami | 
| 3 | https://github.zoom.us/j/312802464 | |
| 4 | https://github.zoom.us/j/477531294 | Tom Janssens, <br>Jamaal Primus, <br>Jason Butler |
| 5 | https://github.zoom.us/j/327833183 | Daniel Esteves Monteiro, <br>Nicholas Patten |
| 6 | https://github.zoom.us/j/972811649 | Shankar Ragunathan, <br>Stian Buch Larsen, <br>Recep Cetin |

We missed on Monday:
- Marlene Spensley 
- Martin Van Soens,
- Tobias Kirchherr 
- Mohammad Chehab,  

<br>Marco Bizzantino
### Day 1

|  Topic | Time per Trainer |
|  ------ | ------ |
|  Introduction - Getting Ready - Getting Started | 6 minutes |
|  GitHub Flow | 6 minutes |
|  Branching with Git | 6 minutes |
|  Local Git Configs | 6 minutes |
|  Working Locally | 11 minutes |
|  Collaborating on Code | 8 minutes |
|  Editing On GitHub | 6 minutes |

### Day 2

|  Topic | Time per Trainer |
|  ------ | ------ |
|  Merging Pull Requests | 9 minutes |
|  Local History | 6 minutes |
|  Streamlining Workflow with Aliases | 6 minutes |
|  Resolving Merge Conflicts | 10 minutes |
|  Day 2 Activity  | 6 minutes |

### Day 3

|  Topic | Time per Trainer |
|  ------ | ------ |
|  Workflow Review | 6 minutes |
|  Git Bisect | 6 minutes |
|  Reverting Commits | 6 minutes |
|  Helpful Git Commands | 13 minutes |
|  Viewing Local Changes | 8 minutes |
|  Tags and Releases | 6 minutes |
|  Small Group Workflow Discussion | 11 minutes |

### Day 4

|  Topic | Time per Trainer |
|  ------ | ------ |
|  Create a Local Repo | 6 minutes |
|  Fixing Commit Mistakes | 9 minutes |
|  Appendix: Fork and Pull Workflow | 6 minutes |
|  Rewriting History with Git Reset  | 13 minutes |
|  Cherry Picking | 8 minutes |
|  Merge Strategies | 8 minutes |

**Comment by Kingerr** [comment]
Martin van Soens was on but dropped off due to the mix-up.  I could not get hold of him after that.
Marlene was supposed to cancel - will remind her to do so.

**Comment by brianamarie** [comment]
@deepakarchinnova, here are the recordings we discussed:

- [Today's recording](https://github.zoom.us/recording/play/JcyJ60FTm1NG_mXTew__U2oUCterKlrBEXG7itdeArG-qxMJd8MDZou2aYpPd6Wt)
- [Recording from open enrollment class](https://vimeo.com/239031515/2990a95426) (Since the recording didn't start immediately today, this will show the content that is missed.)

**Comment by brianamarie** [comment]
> Martin van Soens was on but dropped off due to the mix-up. I could not get hold of him after that.
> Marlene was supposed to cancel - will remind her to do so.

@Kingerr No problem - now that we've got the teachback schedule adjusted, it's not a big deal if she cancels or doesn't cancel. 😄

**Comment by deepakarchinnova** [comment]
👋  @brianamarie , Looks like the below requires a github mail ID to sign in. Or maybe I am doing some thing wrong here. Glad if you could help here. 

> [Today's recording](https://github.zoom.us/recording/play/JcyJ60FTm1NG_mXTew__U2oUCterKlrBEXG7itdeArG-qxMJd8MDZou2aYpPd6Wt)

**Comment by brianamarie** [comment]
> 👋 @brianamarie , Looks like the below requires a github mail ID to sign in. Or maybe I am doing some thing wrong here. Glad if you could help here.

Hi @deepakarchinnova - you're entirely correct! Apologies. I was hoping that we would be able to share directly from zoom, when in fact I will need to download and re-upload on a different platform. I'm uploading it to Vimeo now, and will post the URL here once it's ready. Thank you for the quick feedback so we can get it sorted. 😄

**Comment by brianamarie** [comment]
@deepakarchinnova The video is still converting, but the URL for the video is (or rather will be) here: https://vimeo.com/241510705/e02a7c594f

**Comment by m1crobrain** [comment]
Can I use the top zoom link over the next 2 weeks to record my teachbacks?  I just don't have time this week :-(  https://github.zoom.us/j/563145373 ??

**Comment by brianamarie** [comment]
@m1crobrain Yes. The rooms will be open until November 25th, and all recordings will be automatically uploaded. So even if you can't find time with your group, if you join the room it will still record your teachback so I can give you feedback.

**Comment by brianamarie** [comment]
Day 2 recording: https://vimeo.com/241883460/7d834fd5f3

**Comment by brianamarie** [comment]
Day 3 recording: https://vimeo.com/241885002/ee59479426

**Comment by githubteacher** [comment]
For teachbacks, when using the "merge-conflicts" and "github-games", fork these repositories:

Conflicts: https://github.com/githubtraining/polygons (you will need to create the pull requests, but the branches are there) 

GitHub Games: https://github.com/githubtraining/github-games

**Comment by deepakarchinnova** [comment]
👋  @brianamarie. Can you please post the Day-4 recording as well.

**Comment by brianamarie** [comment]
@deepakarchinnova Unfortunately, The recording for day 4 didn't properly export. 😢 

However, here are two videos showing the day 4 content in real classes:
- [July 13](https://vimeo.com/225442880/b2af82dd9b)
- [August 17](https://vimeo.com/230047474/bbd6fba2b8)
