### ISSUE TITLE
Questions? 

### ISSUE THREAD

**Issue by brianamarie** [githubschool/Nov-6#3]
Please post questions (that we don't answer in class) in this thread, so I will be sure to circle back and answer them.

**Comment by githubteacher** [comment]
Differences between GitLab and GitHub?

**Comment by githubteacher** [comment]
## Briana Notes
- In Pretest, instead of clearing history, just echo into shell and pipe history into file instead of clearing history
- Workflow Consultation should be baked into this content
- Manual edit: Under "Tags & Releases" - Paragraph "Tags" - last sentence has two periods.
- Can we add a script that will generate other copies of the repositories for teachback practice?

**Comment by deepakarchinnova** [comment]
# **Pushback scenario**

**Query** 

1.  Certain customers follow ITIL practices where it becomes difficult to push Github flow though it makes sense but they might have internal processes to be followed. Perhaps there is JIRA issues also as they think they want to go agile. How do we promote Pull Request here. Surely there would be a conversation with some examples, but when it comes to adoption for the organization they have to break down the process in which they were working for the past 10-15 years.
2. Issue fragmentation: Have noticed that sometimes issues created for one purpose can be discussed in a wider context within another issue. This sometimes becomes hard for searching. Is there a best practice to this? I do know we can create a meta link through "#" and mentioning the issue key

**Other Queries**

1. What is the scratch editor used for ? Any links to them would be great to start researching.
2. Are there key points to using Atom?
3. How and where is this configured by default?
<img width="721" alt="screen shot 2017-11-06 at 10 57 11 pm" src="https://user-images.githubusercontent.com/26195566/32458461-fa2fcb4a-c345-11e7-8525-ca9d8e6e6df4.png"> 
4.  What are the key questions we should ask the team to carve out the best flow for the team itself.
5. How can we make Github recognize language patterns? Is this automatic or we have to configure anything ourself.
6. Can we link code/lines of code to issues?

**Comment by brianamarie** [comment]
> Certain customers follow ITIL practices where it becomes difficult to push Github flow though it makes sense but they might have internal processes to be followed. Perhaps there is JIRA issues also as they think they want to go agile. How do we promote Pull Request here. Surely there would be a conversation with some examples, but when it comes to adoption for the organization they have to break down the process in which they were working for the past 10-15 years.

@deepakarchinnova I'm not very familiar with ITIL practices. Could you help me understand these more? I want to address this question, but I want to make sure I understand fully first.

> Issue fragmentation: Have noticed that sometimes issues created for one purpose can be discussed in a wider context within another issue. This sometimes becomes hard for searching. Is there a best practice to this? I do know we can create a meta link through "#" and mentioning the issue key

Yes - exactly. This can be difficult, especially when working among different teams. On my team, we've found a "tracking issue" can be very helpful for large projects, then smaller issues would be used for different pieces. All pieces would be connected with cross links. Additionally, we use project boards in conjunction with tracking issues to keep a pulse on the moving pieces. 

We've seen customers find success in this approach, along with using labels and consistently reviewing open issues to make sure things aren't stale or duplicated. 

> What is the scratch editor used for ? Any links to them would be great to start researching.

I'm not sure I understand - do you mean https://scratch.mit.edu/? 



> Are there key points to using Atom?

Atom is my choice of text editor, because of the huge library of developer made plugins. Atom is "hackable" and very customizable. However, whatever text editor or IDE fits a developer's workflow works fine with Git and GitHub. Visual Studio Code is gaining a lot of popularity, and has a great GitHub plugin. Both Atom and Visual Studio Code are built with Electron. 

> How and where is this configured by default?

Great question - this is configured in "settings" of the repository. I'll show this today. It can also be controlled on the instance level for companies using GHE. 

> What are the key questions we should ask the team to carve out the best flow for the team itself.

This is a great question - we will cover some of them later this week, but I'm reaching out to our Services Engineering team for some more recommendations here that they use in the Workflow Consultation offering. 

> How can we make Github recognize language patterns? Is this automatic or we have to configure anything ourself.

Do you mean spoken languages, or programming languages? What type of recognition are you looking for? 

> Can we link code/lines of code to issues?

Yes. There are ways to do it with direct links, but [the new linking feature that shows the entire code snippet](https://help.github.com/articles/creating-a-permanent-link-to-a-code-snippet/) launched in GitHub Enterprise 2.11. 🎉

**Comment by githubteacher** [comment]
Re: Multiple accounts locally

Turns out the answer is more simple than I had thought - you simply need to set up multiple SSH authentication keys. 

Some of the best docs I found:
http://mherman.org/blog/2013/09/16/managing-multiple-github-accounts/#.WgGePBNSxFI
https://code.tutsplus.com/tutorials/quick-tip-how-to-work-with-github-and-multiple-accounts--net-22574
https://ricardianambivalence.com/2013/09/22/github-for-work-and-play-multiple-accounts/

@deepakarchinnova Let me know if this is the type of answer you were looking for. 😄

**Comment by deepakarchinnova** [comment]
Thanks for the answers  @brianamarie . Given below are the followup questions/statements:

>@deepakarchinnova I'm not very familiar with ITIL practices. Could you help me understand these more? I want to address this question, but I want to make sure I understand fully first.

Adoption of Git and Github is definitely a cultural shift for a team who follows practices like Requirement Gathering, documenting BRD (Business Requirement Document), HLD(High Level Design), LLD (Low Level Design), Project Planning. To refine the question, how can we define the line  between project management tool/practices and Github. For e.g. Developers should stop using mails and use issues. I think unless we state the practice that is required for a hypothetical organization there would only be preaching to use vs actually using it. I know there is easy answer

>I'm not sure I understand - do you mean https://scratch.mit.edu/?

If I recollect you had used scratch from the prompt. Just wondering if that was something github specific feature or not.

> Do you mean spoken languages, or programming languages? What type of recognition are you looking for?

Like Java , php, Python

**Comment by brianamarie** [comment]
> Adoption of Git and Github is definitely a cultural shift for a team who follows practices like Requirement Gathering, documenting BRD (Business Requirement Document), HLD(High Level Design), LLD (Low Level Design), Project Planning. To refine the question, how can we define the line between project management tool/practices and Github. For e.g. Developers should stop using mails and use issues. I think unless we state the practice that is required for a hypothetical organization there would only be preaching to use vs actually using it. I know there is easy answer

Thank you for clarifying here. Figuring out project management tooling is definitely one of the biggest hurdles to adoption that we see. We recommend using Issues, Projects, and Milestones to track progress and manage projects. Some teams find those tools aren't as fully featured as they'd like, so they find luck with some of the integrations. Here are some of the most popular integrations: https://github.com/marketplace/category/project-management



> If I recollect you had used scratch from the prompt. Just wondering if that was something github specific feature or not.

Ah - I see. Nothing special here, 'scratch' is just the name of a directory that I use when working locally for all of my class repositories. 😄 



> Like Java , php, Python
 
GitHub uses the line endings to format the files as legibly as possible based on their language. Is this what you mean?

**Comment by githubteacher** [comment]
How long does "recently pushed branch" pull request button stay around?

**Comment by githubteacher** [comment]
Feature requests:
- Org wide issues
- Let users see issues but not code
- User wide webhooks 

Briana follow up with chatops info and submodule info, don't forget to do tags tomorrow

**Comment by lonix** [comment]
`Feature requests:

Org wide issues
Let users see issues but not code
User wide webhooks
Briana follow up with chatops info and submodule info, don't forget to do tags tomorrow`

@githubteacher  and Releases !

**Comment by githubteacher** [comment]
Chatbot info: https://github.com/universeworkshops/universe-bot 
Submodule outline: https://gist.github.com/brianamarie/b5e55cca15c1ac8108e75a8e4a2225eb

**Comment by deepakarchinnova** [comment]
> Differences between GitLab and GitHub?

A basic comparo compiled with a lot of help from Github. 

[Github vs Others-A Basic Comparo.docx](https://github.com/githubschool/Nov-6/files/1454788/Github.vs.Others-A.Basic.Comparo.docx)

**Comment by deepakarchinnova** [comment]
👋  @brianamarie 

Is there a way to fork or have a repo similar to the githubschool/conflict-practice-<username> to reuse for teach back and further also. If not, any tips on recreating the 3rd scenario; conflict resolution on local.

**Comment by brianamarie** [comment]
> Is there a way to fork or have a repo similar to the githubschool/conflict-practice- to reuse for teach back and further also. If not, any tips on recreating the 3rd scenario; conflict resolution on local.

@deepakarchinnova Yes - When I send the copies of the "training manual" for internal use, I'll include copies of the 'github games' and 'conflict-practice' repositories.

**Comment by githubteacher** [comment]
https://resources.github.com/webcasts/

https://github.com/praqma-training/gitkatas

**Comment by githubteacher** [comment]
BFG Repo Cleaner: https://rtyley.github.io/bfg-repo-cleaner/
